# fly.toml app configuration file generated for discord-bot-leetcode on 2025-08-21T19:52:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-bot-leetcode'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  cpus = 2
  cpu_kind = "shared"
  memory = "512"